// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlmdrsubrbbrhscjuugg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbWRyc3VicmJicmhzY2p1dWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDYzMDEsImV4cCI6MjA2MDM4MjMwMX0.KXt9hCy0fTJBKzGYa5R1uxlx3G39zcLELk76dfUcQ-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);